DROP TABLE IF EXISTS people CASCADE;

CREATE TABLE people
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar NOT NULL,
    birth_year int     NOT NULL
);

CREATE TABLE books
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES people (id),
    title     varchar NOT NULL,
    author    varchar NOT NULL,
    year      int     NOT NULL
);