DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS people;

CREATE TABLE people
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar NOT NULL,
    birth_year int     NOT NULL
);

CREATE TABLE books
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int     REFERENCES people (id) ON DELETE SET NULL,
    title     varchar NOT NULL,
    author    varchar NOT NULL,
    year      int     NOT NULL,
    taken_at  timestamp
);